import 'package:flutter_test/flutter_test.dart';
import 'package:core_shared/core_shared.dart';
void main(){
 test('greeting honors Manila boundaries and 3 PM',(){expect(greeting(DateTime.utc(2026,9,25,7)),'Good Afternoon!');expect(greeting(DateTime.utc(2026,9,25,3,59)),'Good Morning!');expect(greeting(DateTime.utc(2026,9,25,4)),'Good Afternoon!');expect(greeting(DateTime.utc(2026,9,25,10)),'Good Evening!');});
 test('counts are unique patients and explicit status groups',(){final r=CareRepository.demo();addTearDown(r.dispose);final c=dashboardCounts(r.sessions,DateTime.now());expect(c,{'Total Patients Today':6,'Active Sessions':1,'Pending':2,'Completed':2});r.sessions.add(CareRecord('extra',{...r.sessions.first.data}));expect(dashboardCounts(r.sessions,DateTime.now())['Total Patients Today'],6);});
 test('completion and pickup notifications are distinct and audited',()async{final r=CareRepository.demo();addTearDown(r.dispose);final s=r.sessions[2];await r.command('transition',{'id':s.id,'version':1,'status':'Completed'});expect(r.notifications.where((n)=>n.text('type')=='Ready for Pickup'),isEmpty);await r.command('transition',{'id':s.id,'version':2,'status':'Ready for Pickup'});expect(r.notifications.where((n)=>n.text('type')=='Ready for Pickup'),hasLength(1));await expectLater(r.command('transition',{'id':s.id,'version':2,'status':'Ready for Pickup'}),throwsStateError);expect(r.audit,hasLength(2));expect(r.notifications.last.text('state'),'Demo only - not sent');});
 test('conflicts, cancellation, stale edits and role restrictions',()async{final r=CareRepository.demo();addTearDown(r.dispose);final s=r.sessions.first;await expectLater(r.command('saveSchedule',{'id':'conflict',...s.data}),throwsStateError);await r.command('transition',{'id':s.id,'version':1,'status':'Cancelled','reason':'test'});expect(dashboardCounts(r.sessions,DateTime.now())['Total Patients Today'],5);final relative=CareRepository.demo(role:'relative');addTearDown(relative.dispose);await expectLater(relative.command('saveSchedule',s.data),throwsStateError);});
 test('escalation requires refusal or timeout',()async{final r=CareRepository.demo();addTearDown(r.dispose);final s=r.sessions[4];await expectLater(r.command('escalate',{'id':s.id}),throwsStateError);s.data['pickupResponse']='Cannot Pick Up';await r.command('escalate',{'id':s.id});expect(s.data['escalated'],true);await expectLater(r.command('escalate',{'id':s.id}),throwsStateError);});
}
