const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const enabled=!!process.env.FIRESTORE_EMULATOR_HOST;
let env,db,command;let n=0;
const projectId='demo-dialycare';
before(async()=>{if(!enabled)return;process.env.GCLOUD_PROJECT=projectId;
 const {initializeTestEnvironment}=require('@firebase/rules-unit-testing');
 env=await initializeTestEnvironment({projectId,firestore:{rules:fs.readFileSync('../firestore.rules','utf8')}});
 await env.clearFirestore();const functions=require('./index.js');command=functions.careCommand.run;
 db=require('firebase-admin/firestore').getFirestore();
 for(const [uid,role]of [['staff','staff'],['admin','admin'],['patient','patient'],['relative','relative'],['emergency','relative'],['outsider','relative']])await db.doc('dcUsers/'+uid).set({role,active:true,centerId:uid==='outsider'?'other':'center'});
 await db.doc('dcCenters/center').set({name:'Test Center',escalationMinutes:15});
});
after(async()=>{if(env)await env.cleanup();if(db)await db.terminate();});
const call=(uid,data)=>command({auth:{uid,token:{}},data:{centerId:'center',requestId:'request-'+(++n),...data}});
test('transactional workflow, authorization, duplicate suppression and audit',{skip:!enabled},async()=>{
 const patient={action:'savePatient',id:'p1',name:'Test Person',birth:'1970-01-01',contact:'+639170000000',address:'Test',patientUid:'patient',relativeUid:'relative',relativeName:'Relative',relativePhone:'+639170000001',emergencyUid:'emergency',emergencyName:'Emergency',emergencyPhone:'+639170000002'};
 await assert.rejects(call('relative',patient));await call('staff',patient);
 const start=Date.now()+3600000;await call('staff',{action:'saveSchedule',id:'s1',patientId:'p1',room:'Room 1',batch:'Batch C',startMs:start,endMs:start+3600000});
 await assert.rejects(call('staff',{action:'saveSchedule',id:'s2',patientId:'p1',room:'Room 2',batch:'Batch A',startMs:start,endMs:start+3600000}));
 const change={action:'transition',id:'s1',status:'Waiting',version:1,reason:'checked in',requestId:'same-request'};await call('staff',change);await call('staff',change);
 let s=(await db.doc('dcCenters/center/sessions/s1').get()).data();assert.equal(s.version,2);
 await assert.rejects(call('staff',{action:'transition',id:'s1',version:1,status:'In Progress'}));
 await call('staff',{action:'transition',id:'s1',version:2,status:'In Progress'});
 await call('staff',{action:'transition',id:'s1',version:3,status:'Completed'});
 let notices=await db.collection('dcCenters/center/notifications').get();assert.equal(notices.docs.filter(n=>n.data().type==='Ready for Pickup').length,0);
 await call('staff',{action:'transition',id:'s1',version:4,status:'Ready for Pickup'});
 notices=await db.collection('dcCenters/center/notifications').get();assert.equal(notices.docs.filter(n=>n.data().type==='Ready for Pickup').length,1);
 await assert.rejects(call('patient',{action:'respondPickup',id:'s1',pickupGeneration:1,response:'I Can Pick Up'}));
 await assert.rejects(call('staff',{action:'escalate',id:'s1'}));
 await call('relative',{action:'respondPickup',id:'s1',pickupGeneration:1,response:'Cannot Pick Up'});
 await call('staff',{action:'escalate',id:'s1',reason:'relative unavailable'});
 await assert.rejects(call('relative',{action:'respondPickup',id:'s1',pickupGeneration:1,response:'I Can Pick Up'}));
 await call('emergency',{action:'respondPickup',id:'s1',pickupGeneration:2,response:'I Can Pick Up'});
 s=(await db.doc('dcCenters/center/sessions/s1').get()).data();await call('staff',{action:'transition',id:'s1',version:s.version,status:'Picked Up',reason:'Handover confirmed'});
 assert.ok((await db.collection('dcCenters/center/audit').get()).size>=9);
});
test('Firestore rules deny role forgery, cross-center access and unscoped queries',{skip:!enabled},async()=>{
 const {assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');const {doc,getDoc,setDoc,collection,getDocs,query,where}=require('firebase/firestore');
 await db.doc('dcCenters/center/sessions/rules-session').set({viewerUids:['patient','relative'],patientName:'Authorized summary'});
 await db.doc('dcCenters/center/patients/private').set({notes:'Private medical notes'});
 const relative=env.authenticatedContext('relative').firestore(),staff=env.authenticatedContext('staff').firestore(),outside=env.authenticatedContext('outsider').firestore();
 await assertSucceeds(getDoc(doc(relative,'dcCenters/center/sessions/rules-session')));
 await assertFails(getDoc(doc(outside,'dcCenters/center/sessions/rules-session')));
 await assertFails(getDoc(doc(relative,'dcCenters/center/patients/private')));
 await assertSucceeds(getDoc(doc(staff,'dcCenters/center/patients/private')));
 await assertFails(setDoc(doc(relative,'dcUsers/relative'),{role:'admin',active:true,centerId:'center'}));
 await assertFails(setDoc(doc(staff,'dcCenters/center/sessions/hacked'),{status:'Completed'}));
 await assertFails(getDocs(collection(relative,'dcCenters/center/sessions')));
 await assertSucceeds(getDocs(query(collection(relative,'dcCenters/center/sessions'),where('viewerUids','array-contains','relative'))));
 await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'dcCenters/center/sessions/rules-session')));
});
